#!/usr/bin/env python3
"""
Assemble the self-contained MediaWiki bundle.

The wiki gadget used to load five scripts from an externally deployed copy
of the site. That meant every article using {{Avatarian}} reached out to
GitHub/Cloudflare Pages. This bundles the same five modules — plus the
render step in wiki/gadget.js — into ONE file that lives on the wiki as
[[MediaWiki:Avatarian.js]], so nothing is fetched from an outside server.
The glyphs are already inline SVG in manifest.js, so there are no external
images either: the whole thing is served by the wiki.

The 1.6 MB pronunciation dictionary (lexicon.js) is deliberately left out,
exactly as the old gadget left it out — far too heavy for a page that may
draw one word, and g2p's rules cover the en= case.

Run:  python3 tools/build_wiki_bundle.py
Then paste wiki/MediaWiki_Avatarian.js.txt into [[MediaWiki:Avatarian.js]].
Re-run whenever any of the bundled site/js modules change.
"""

import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SITE_JS = ROOT / "site" / "js"
GADGET = ROOT / "wiki" / "gadget.js"
OUT = ROOT / "wiki" / "MediaWiki_Avatarian.js.txt"

# Order matters: sounds.js reads g2p.js's ARPAbet table, and render.js
# reads the manifest and corpus. Same order the standalone site loads them.
MODULES = ["manifest.js", "corpus.js", "g2p.js", "sounds.js", "render.js"]

HEADER = (
    "/* Avatarian — self-contained MediaWiki bundle. DO NOT EDIT BY HAND.\n"
    " * Generated by tools/build_wiki_bundle.py from site/js/* + wiki/gadget.js.\n"
    " * Paste into [[MediaWiki:Avatarian.js]]; the loader in\n"
    " * [[MediaWiki:Common.js]] fetches it from the wiki, so no outside\n"
    " * server is touched. Credits and sources: see AVATARIAN.md. */\n"
)


def section(name, text):
    bar = "=" * 66
    return f"\n/* {bar}\n   {name}\n   {bar} */\n{text.rstrip()}\n"


def main():
    parts = [HEADER]
    for name in MODULES:
        src = (SITE_JS / name).read_text(encoding="utf-8")
        parts.append(section(f"site/js/{name}", src))
    parts.append(section("wiki/gadget.js", GADGET.read_text(encoding="utf-8")))

    bundle = "".join(parts).rstrip() + "\n"
    OUT.write_text(bundle, encoding="utf-8")

    kb = len(bundle.encode("utf-8")) / 1024
    print(f"Wrote {OUT.relative_to(ROOT)} — "
          f"{len(MODULES) + 1} modules, {kb:.0f} KB.")


if __name__ == "__main__":
    main()
