#!/usr/bin/env python3
"""
Emit the attested corpus as a MediaWiki table, for pasting onto a wiki
that has the {{Avatarian}} gadget. Each row draws the word in Avatarian
(via the template), beside its English, IPA and sighting count. Each
spelling's source is a named <ref> footnote (one per source, reused);
a contested word — its sources spell it more than one way — carries a
<ref group="note"> note and shows every spelling. The table ends with a
== Sources == <references/> and a == Notes == <references group="note"/>.

Reads the compiled corpus (site/js/corpus.js) and sounds.js's own READABLE
table, so the codes match what the tool types.

Run:  python3 tools/build_corpus_wikitable.py
Writes wiki/Corpus_table.wiki; paste it into an article.
"""

import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
CORPUS = ROOT / "site" / "js" / "corpus.js"
SOUNDS = ROOT / "site" / "js" / "sounds.js"
OUT = ROOT / "wiki" / "Corpus_table.wiki"


def ipa_to_code():
    """IPA -> readable code, built from sounds.js's READABLE first-wins, so
    it matches soundToCode in the app. `∅` shows as its `0` filler."""
    m = re.search(r"READABLE\s*=\s*\{(.*?)\n\};", SOUNDS.read_text(encoding="utf-8"), re.S)
    out = {"∅": "0"}
    for code, ipa in re.findall(r'"([^"]+)"\s*:\s*"([^"]+)"', m.group(1)):
        out.setdefault(ipa, code)
    return out


CODE = ipa_to_code()


def sounds(ipa):
    """An IPA list -> the template's sounds parameter (readable codes, nulls
    and $/% orientation overrides carried through)."""
    out = []
    for tok in ipa:
        body, suffix = (tok[:-1], tok[-1]) if tok[-1:] in "$%" else (tok, "")
        out.append(CODE.get(body, body) + suffix)
    return " ".join(out)


def clean_ipa(ipa):
    """The pronunciation to show: no nulls, no orientation overrides."""
    return " ".join(t.rstrip("$%") for t in ipa if t not in ("∅", "∅c"))


def spellings(word):
    """Every distinct spelling of a word — the winning one, then alternates."""
    yield word["ipa"], word.get("sources", [])
    for alt in word.get("alternates", []):
        yield alt["ipa"], alt.get("sources", [])


def main():
    m = re.search(r"window\.AVATARIAN_CORPUS\s*=\s*(\{.*\n\});",
                  CORPUS.read_text(encoding="utf-8"), re.S)
    corpus = json.loads(m.group(1))
    words, sources = corpus["words"], corpus.get("sources", {})

    def label_of(key, word):
        return word.get("gloss") or key

    # Each source becomes a named footnote, defined once and reused, so the
    # references list has one entry per source rather than a duplicate per
    # word. Definition order doesn't matter to MediaWiki, but we define on
    # first use anyway.
    defined = set()

    def source_ref(sid):
        if sid in defined:
            return '<ref name="%s" />' % sid
        defined.add(sid)
        s = sources.get(sid, {})
        where = s.get("where", "")
        if where.startswith("http"):
            desc = " — [%s post]" % where
        elif where:
            desc = " — %s" % where
        else:
            desc = ""
        return '<ref name="%s">\'\'%s\'\'%s</ref>' % (sid, sid, desc)

    note_defined = [False]

    def contested_note():
        if note_defined[0]:
            return '<ref group="note" name="contested" />'
        note_defined[0] = True
        return ('<ref group="note" name="contested">Its sources spell this '
                'word more than one way; each spelling is shown.</ref>')

    rows = []
    for key, word in sorted(words.items(),
                            key=lambda kv: label_of(*kv).lower()):
        label = label_of(key, word)
        note = contested_note() if word.get("contested") else ""
        # One {{Avatarian}} per distinct spelling; each carries its own
        # source refs. Contested words show every spelling.
        cells = []
        for ipa, srcs in spellings(word):
            refs = "".join(source_ref(s) for s in srcs)
            cells.append("{{Avatarian|%s|%s}}%s" % (sounds(ipa), label, refs))
        rows.append("| %s%s || %s || /%s/ || %d"
                    % (label, note, "<br>".join(cells),
                       clean_ipa(word["ipa"]), word.get("count", 1)))

    table = (
        "<!-- Generated by tools/build_corpus_wikitable.py — do not edit by hand. -->\n"
        "The attested Avatarian corpus: every word someone has been seen to "
        "write, drawn from its recorded spelling. The footnote on each "
        "spelling is the source it was read off; a note<sup>[?]</sup> beside "
        "a word means its sources spell it more than one way, and every "
        "spelling is shown.\n\n"
        '{| class="wikitable sortable"\n'
        "|+ Attested Avatarian corpus\n"
        "! Word !! Avatarian !! IPA !! Seen\n"
        "|-\n"
        + "\n|-\n".join(rows)
        + "\n|}\n\n"
        "== Sources ==\n<references />\n\n"
        "== Notes ==\n<references group=\"note\" />\n"
    )
    OUT.write_text(table, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} — {len(rows)} words, "
          f"{len(defined)} sources.")


if __name__ == "__main__":
    main()
