#!/usr/bin/env python3
"""
Emit the attested corpus as a MediaWiki table, for pasting onto a wiki
that has the {{Avatarian}} gadget. Each row draws the word in Avatarian
(via the template), beside its English, IPA, sighting count and sources.

Reads the compiled corpus (site/js/corpus.js) and sounds.js's own READABLE
table, so the codes match what the tool types. Contested words (sources
disagreeing on the spelling) show every distinct spelling.

Run:  python3 tools/build_corpus_wikitable.py
Writes wiki/Corpus_table.wiki; paste it into an article.
"""

import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
CORPUS = ROOT / "site" / "js" / "corpus.js"
SOUNDS = ROOT / "site" / "js" / "sounds.js"
OUT = ROOT / "wiki" / "Corpus_table.wiki"


def ipa_to_code():
    """IPA -> readable code, built from sounds.js's READABLE first-wins, so
    it matches soundToCode in the app. `∅` shows as its `0` filler."""
    m = re.search(r"READABLE\s*=\s*\{(.*?)\n\};", SOUNDS.read_text(encoding="utf-8"), re.S)
    out = {"∅": "0"}
    for code, ipa in re.findall(r'"([^"]+)"\s*:\s*"([^"]+)"', m.group(1)):
        out.setdefault(ipa, code)
    return out


CODE = ipa_to_code()


def sounds(ipa):
    """An IPA list -> the template's sounds parameter (readable codes, nulls
    and $/% orientation overrides carried through)."""
    out = []
    for tok in ipa:
        body, suffix = (tok[:-1], tok[-1]) if tok[-1:] in "$%" else (tok, "")
        out.append(CODE.get(body, body) + suffix)
    return " ".join(out)


def clean_ipa(ipa):
    """The pronunciation to show: no nulls, no orientation overrides."""
    return " ".join(t.rstrip("$%") for t in ipa if t not in ("∅", "∅c"))


def spellings(word):
    """Every distinct spelling of a word — the winning one, then alternates."""
    yield word["ipa"], word.get("sources", [])
    for alt in word.get("alternates", []):
        yield alt["ipa"], alt.get("sources", [])


def main():
    m = re.search(r"window\.AVATARIAN_CORPUS\s*=\s*(\{.*\n\});",
                  CORPUS.read_text(encoding="utf-8"), re.S)
    words = json.loads(m.group(1))["words"]

    def label_of(key, word):
        return word.get("gloss") or key

    rows = []
    for key, word in sorted(words.items(),
                            key=lambda kv: label_of(*kv).lower()):
        label = label_of(key, word)
        # One {{Avatarian}} per distinct spelling; contested words show all.
        avatarian, srcs = [], []
        for ipa, sources in spellings(word):
            avatarian.append("{{Avatarian|%s|%s}}" % (sounds(ipa), label))
            srcs += sources
        cell = "<br>".join(avatarian)
        seen = word.get("count", 1)
        srclist = ", ".join(dict.fromkeys(srcs))       # de-duped, in order
        note = " ''(contested)''" if word.get("contested") else ""
        rows.append("| %s || %s || /%s/ || %d || %s%s"
                    % (label, cell, clean_ipa(word["ipa"]), seen, srclist, note))

    table = (
        "<!-- Generated by tools/build_corpus_wikitable.py — do not edit by hand. -->\n"
        "The attested Avatarian corpus: every word someone has been seen to "
        "write, drawn from its recorded spelling. A word marked "
        "''contested'' is one its sources spell more than one way; each "
        "spelling is shown.\n\n"
        '{| class="wikitable sortable"\n'
        "|+ Attested Avatarian corpus\n"
        "! Word !! Avatarian !! IPA !! Seen !! Sources\n"
        "|-\n"
        + "\n|-\n".join(rows)
        + "\n|}\n"
    )
    OUT.write_text(table, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} — {len(rows)} words.")


if __name__ == "__main__":
    main()
